# Generated by Django 6.1.1 on 2026-09-22 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquacare', '0002_alter_alert_id_alter_alertacknowledgement_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='District name (e.g. Varanasi, Prayagraj)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Administrative district code (e.g. DIST-VAR)', max_length=50, unique=True)),
                ('state', models.CharField(default='Uttar Pradesh', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='village',
            new_name='aquacare_vi_distric_f4baef_idx',
            old_name='aquacare_vi_distric_a08f05_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='assigned_villages',
        ),
        migrations.AddField(
            model_name='village',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, help_text='Field Health Worker assigned to this village (each village has exactly one worker; a worker can cover multiple villages)', limit_choices_to={'role': 'HEALTH_WORKER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_villages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='village',
            name='authority',
            field=models.ForeignKey(blank=True, help_text='Health Authority overseeing this village (10-15 villages per authority)', limit_choices_to={'role': 'AUTHORITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_villages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='authority',
            field=models.ForeignKey(blank=True, help_text='Chief Health Authority assigned to oversee this district', limit_choices_to={'role': 'AUTHORITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_districts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='village',
            name='district',
            field=models.ForeignKey(help_text='District to which this village belongs (5-10 districts total)', on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='aquacare.district'),
        ),
    ]
